# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openbattery < Formula
  desc "TUI battery monitor for macOS"
  homepage "https://github.com/przybylku/openbattery"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/przybylku/openbattery/releases/download/v0.1.0/openbattery_0.1.0_darwin_amd64.tar.gz"
    sha256 "d1caea3c86cc0c4534e6503b20281e4d6cf749d39f0a5dd998470bdfefe197d2"

    define_method(:install) do
      bin.install "openbattery"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/przybylku/openbattery/releases/download/v0.1.0/openbattery_0.1.0_darwin_arm64.tar.gz"
    sha256 "e762d0183d62abee9e2d20f4ccaf92ba68a4b78b5a62078e498ed94c4b66ad73"

    define_method(:install) do
      bin.install "openbattery"
    end
  end

  test do
    system "#{bin}/openbattery", "--help"
  end
end
