# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openbattery < Formula
  desc "TUI battery monitor for macOS"
  homepage "https://github.com/przybylku/openbattery"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/przybylku/openbattery/releases/download/v0.1.0/openbattery_0.1.0_darwin_amd64.tar.gz"
    sha256 "0942347496c9eec874ca2184d4041f6896c41ffa9db55416c6d52ddc9e3175a1"

    define_method(:install) do
      bin.install "openbattery"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/przybylku/openbattery/releases/download/v0.1.0/openbattery_0.1.0_darwin_arm64.tar.gz"
    sha256 "522caad3e2f3273de97c970347d40e77d8a0f96596abf811573aee73b79b0566"

    define_method(:install) do
      bin.install "openbattery"
    end
  end

  test do
    system "#{bin}/openbattery", "--help"
  end
end
